services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
     - shared_network

  api-gateway-service:
    container_name: api-gateway-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    volumes:
      - ./.env:/app/.env
    networks:
      - shared_network

networks:
  shared_network:
    external: true