// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	dbpb "github.com/rail52/myprojects/dbpb"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// Creator is an autogenerated mock type for the Creator type
type Creator struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: ctx, in, opts
func (_m *Creator) CreateTask(ctx context.Context, in *dbpb.CreateTaskRequest, opts ...grpc.CallOption) (*dbpb.Task, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *dbpb.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dbpb.CreateTaskRequest, ...grpc.CallOption) (*dbpb.Task, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dbpb.CreateTaskRequest, ...grpc.CallOption) *dbpb.Task); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbpb.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dbpb.CreateTaskRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCreator creates a new instance of Creator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Creator {
	mock := &Creator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
