// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	requests "todo-app/internal/domain/requests"

	mock "github.com/stretchr/testify/mock"
)

// KafkaProducer is an autogenerated mock type for the KafkaProducer type
type KafkaProducer struct {
	mock.Mock
}

// SendApiEvent provides a mock function with given fields: apiRequest
func (_m *KafkaProducer) SendApiEvent(apiRequest *requests.ApiRequest) error {
	ret := _m.Called(apiRequest)

	if len(ret) == 0 {
		panic("no return value specified for SendApiEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*requests.ApiRequest) error); ok {
		r0 = rf(apiRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKafkaProducer creates a new instance of KafkaProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKafkaProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *KafkaProducer {
	mock := &KafkaProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
