services:
  auth-service-postgres:
    container_name: auth-service-postgres
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - shared_network

  auth-service-redis:
    container_name:  auth-service-redis
    image: redis:7-alpine
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always
    networks:
      - shared_network

  auth-service:
    image: auth-service
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    networks:
      - shared_network
    depends_on:
      - auth-service-postgres
      - auth-service-redis
  

volumes:
  postgres_data:
  redis_data:

networks:
  shared_network:
    external: true
    