migrate-up:
	migrate -path ./migrations -database "postgres://admin:123@localhost:5432/mentors?sslmode=disable" up

migrate-down:
	migrate -path ./migrations -database "postgres://admin:123@localhost:5432/mentors?sslmode=disable" down